PREFIX :      <http://www.swows.org/samples/WorldInfo#>
PREFIX xml:   <http://www.swows.org/xml#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time:   <http://www.swows.org/time#>
PREFIX tuio:  <http://www.swows.org/tuio#>
PREFIX events:  <http://www.swows.org/DOM/Events#>
PREFIX doc:   <http://www.swows.org/xml/instance#>
PREFIX local: <file:///home/miguel/git/WorldInfo/svg/>

INSERT { swi:GraphRoot :selectedOption ?newOption }
WHERE {
  GRAPH :startingOption { swi:GraphRoot :selectedOption ?newOption } .
  FILTER NOT EXISTS{ swi:GraphRoot :selectedOption ?anyOption } .
};

DELETE { swi:GraphRoot :selectedOption ?oldOption }
INSERT { swi:GraphRoot :selectedOption ?newOption }
WHERE {
  swi:GraphRoot :selectedOption ?oldOption.
  GRAPH swi:mouseEvents {
    ?event a events:MouseEvent ; events:target ?eventTarget .
  } .
  GRAPH :config { swi:GraphRoot :possibleOption/:id ?newOption }
  FILTER (
    URI( CONCAT( STR(local:BlankMapWithRadioBox.svg), "#option_", ?newOption, "_radioBorder" ) )
        = ?eventTarget ).
  FILTER ( ?newOption != ?oldOption ).
};

