PREFIX :      <http://www.cattid.uniroma1.it/2012/pampers#>
PREFIX xml:   <http://www.swows.org/xml#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX swi:   <http://www.swows.org/instance#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time:   <http://www.swows.org/time#>
PREFIX tuio:  <http://www.swows.org/tuio#>
PREFIX events:  <http://www.swows.org/DOM/Events#>
PREFIX doc:   <http://www.swows.org/xml/instance#>

DELETE { swi:GraphRoot :selectedOption ?oldOption }
INSERT { swi:GraphRoot :selectedOption ?newOption }
WHERE {
  GRAPH swi:ThisGraph { swi:GraphRoot :selectedOption ?oldOption }
  GRAPH swi:AddedGraph {
    ?event a events:MouseEvent ; events:target ?eventTarget .
  } .
  swi:GraphRoot :possibleOption ?newOption .
  FILTER (
    URI( CONCAT( STR(doc:option_), ?newOption, "_radioBorder" ) )
        = ?eventTarget ).
};

