PREFIX :      <http://www.swows.org/samples/WorldInfo#>
PREFIX xml:   <http://www.swows.org/xml#>

CONSTRUCT {
  ?node :descendantOrSelf ?descendantOrSelf .
}
WHERE {
  ?node xml:hasChild* ?descendantOrSelf .
}

